name: "ensemble_face"
platform: "ensemble"
max_batch_size: 0

input [
   {
      name: "input"
      data_type: TYPE_FP32
      dims: [1,3,640,640]
   }
]

output [
   {
     name: "output_image"
     data_type: TYPE_FP32
     dims: [-1,16800,16]
   }
]

ensemble_scheduling {
    step [
        {
            model_name: "face_detr_sub"
            model_version: 1
            input_map {
               key: "input0"
               value: "input"
            }

            output_map {
               key: "output0"
               value: "det_output"
            }
        },
        {
           model_name: "facedet_post_sub"
           model_version: 1
           input_map {
               key: "detr_image"
               value: "det_output"
           }

           input_map {
              key: "input"
              value: "input"
           }

           output_map {
               key: "image_output"
               value: "output_image"
           }
        }
    ]
}

