name: "car_det_sub"
backend: "onnxruntime"
max_batch_size: 0

input [
  {
     name: "input0"
     data_type: TYPE_FP32
     dims: [1,3,640,640]
  }
]

output [
  {
      name: "output0"
      data_type: TYPE_FP32
      dims: [1,25200,6]
  }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]

