name: "facedet_post_sub"
backend: "python"
max_batch_size: 0

input [
   {
     name: "detr_image"
     data_type: TYPE_FP32
     dims: [-1,16800,16]
   },
   {
     name: "input"
     data_type: TYPE_FP32
     dims: [1,3,640,640]
   }
]

output [
    {
        name: "image_output"
        data_type: TYPE_FP32
        dims: [-1,16800,16]
    }
]


instance_group [
    {
        kind: KIND_CPU
    }
]
