name: "yolov3"
backend: "onnxruntime"
max_batch_size: 8

input [
  {
    name: "input0"
    data_type: TYPE_FP32
    dims: [3,416,416]
  }
]


output [
   {
     name: "output0"
     data_type: TYPE_FP32
     dims: [2535,85]
   }
]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]